jwt:
  secret: "JWT_SECRET_LUCKY_MARKET"
  ttl: '7d'

postgres:
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "lucky_market"

mongo:
  uri: "mongodb://localhost:27017"
  dbName: "lucky_market"

redis:
  host: "localhost"
  port: 6379
  dbs:
    default: 0
  ttls:
    default: 0

# use bcrypt for hashing
hashing:
  rounds: 8
