jwt:
  secret: "JWT_SECRET_LUCKY_MARKET"

postgres:
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "lucky_market"

redis:
  host: "localhost"
  port: 6379
  dbs:
    default: 0
  ttls:
    default: 0

hashing:
  passwordSecret: "agFWNuQ4NNUvYSTh"
